#!/usr/bin/env python3
"""Run three independent mixed-schedule VulEx repetitions."""

from __future__ import annotations

import argparse
import json
import os
import pathlib
import statistics
import sys
from typing import Any

ROOT = pathlib.Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from experiments.vulex import run_experiment


class GeneratedSnippetClient:
    """Replay snippets generated by build.sh by request ID."""

    def __init__(self, path: pathlib.Path) -> None:
        """Load the snippet index."""
        payload = json.loads(path.read_text(encoding="utf-8"))
        self.by_request_id = {str(row["request_id"]): str(row["snippet"]) for row in payload["rows"]}

    def complete(self, purpose: str, model: str, prompt: str, request_id: str) -> str:
        """Allow replay only for validated snippets."""
        if purpose != "sss":
            raise ValueError(f"unexpected generated snippet purpose: {purpose}")
        if request_id not in self.by_request_id:
            raise KeyError(f"missing generated snippet for request {request_id}")
        return self.by_request_id[request_id]


def runner_args(config: dict[str, Any], repeat: int, resume: bool) -> list[str]:
    """Build run_experiment arguments from the top-level config."""
    inputs, generated, schedule, sss, runtime = (
        config["inputs"], config["generated"], config["schedule"], config["sss"], config["runtime"]
    )
    cap_bank = ROOT / generated["cap_bank"]
    sss_bank = ROOT / generated["sss_bank"]
    output = ROOT / runtime["outputs"] / f"repeat_{repeat}"
    args = [
        "--memory", str(ROOT / inputs["vulnerability_memory"]),
        "--ordinary-memory", str(ROOT / inputs["ordinary_memory"]),
        "--records", str(ROOT / inputs["records"]),
        "--budget", str(schedule["budget"]),
        "--agent-model", os.environ.get("VULEX_AGENT_MODEL", runtime["agent_model"]),
        "--sss-model", sss["snippet_model"],
        "--visibility-split", str(ROOT / inputs["visibility_split"]),
        "--cwe-source", str(ROOT / inputs["cwe_source"]),
        "--cap-budget", str(schedule["cap_queries"]),
        "--sss-payload-bank", str(sss_bank),
        "--cap-anchor-bank", str(cap_bank),
        "--repo-worktree", "",
        "--openai-api-base", os.environ.get("VULEX_OPENAI_API_BASE", runtime["openai_api_base"]),
        "--openclaw-served-memory-policy", runtime["openclaw_served_memory_policy"],
        "--openclaw-memory-search", runtime["openclaw_memory_search"],
        "--docker-image", runtime["docker_image"],
        "--agent-timeout", str(runtime["agent_timeout_seconds"]),
        "--out", str(output),
    ]
    if resume:
        args.append("--resume")
    return args


def aggregate(config: dict[str, Any]) -> dict[str, Any]:
    """Aggregate scored summaries from the three runs."""
    output_root = ROOT / config["runtime"]["outputs"]
    summaries = [
        json.loads((output_root / f"repeat_{repeat}" / "summary_scored.json").read_text(encoding="utf-8"))
        for repeat in range(1, config["schedule"]["repeats"] + 1)
    ]
    numeric_keys = sorted(
        key for key, value in summaries[0].items()
        if isinstance(value, (int, float)) and all(isinstance(row.get(key), (int, float)) for row in summaries)
    )
    payload = {
        "repeats": len(summaries),
        "metrics": {
            key: {
                "mean": statistics.mean(float(row[key]) for row in summaries),
                "sample_std": statistics.stdev(float(row[key]) for row in summaries),
            }
            for key in numeric_keys
        },
        "runs": summaries,
    }
    (output_root / "aggregate.json").write_text(
        json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    return payload


def main(argv: list[str] | None = None) -> None:
    """Run all repetitions and generate the aggregate."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default="config.json")
    parser.add_argument("--resume", action="store_true")
    args = parser.parse_args(argv)
    config = json.loads((ROOT / args.config).read_text(encoding="utf-8"))
    snippet_client = GeneratedSnippetClient(ROOT / config["generated"]["snippets"])
    for repeat in range(1, config["schedule"]["repeats"] + 1):
        run_experiment.main(runner_args(config, repeat, args.resume), llm=snippet_client)
    aggregate(config)


if __name__ == "__main__":
    main()
